name: Post-test
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
      - requested

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      output1: steps.random-color-generator.outputs.SELECTED_COLOR
      
    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github.event_name }}
      
      - name: Dump GitHub Event context
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event.workflow_run) }}
        run: echo "$GITHUB_EVENT_CONTEXT"
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
        
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::blue'
        id: random-color-generator
        
      - name: Get color
        if: steps.random-color-generator.outputs.SELECTED_COLOR
        run: echo 'The selected color is' ${{steps.random-color-generator.outputs.SELECTED_COLOR}}
